development:
  sessions:
    sim_back:
      database: simback_dev
      hosts:
        - localhost:27017

test:
  sessions:
    sim_back:
      database: simback_test
      hosts:
        - localhost:27017